<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.haveno-dex.netlayer</groupId>
    <artifactId>parent</artifactId>
    <version>0.7.10</version>
    <packaging>pom</packaging>

    <name>Netlayer</name>

    <properties>
        <!-- General -->
        <java.version>21</java.version>
        <kotlin.version>2.3.21</kotlin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- Maven plugins -->
        <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
        <!-- Tor browser version 15.0.22 with tor binary version 0.4.9.12 -->
        <tor-binary.version>f5a4bedeb467fd0f063bd572a9e71d9d239c3523</tor-binary.version>
    </properties>

    <modules>
        <module>tor</module>
        <module>tor.native</module>
        <module>tor.external</module>
    </modules>

   <repositories>
       <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
    
    <dependencies>
         <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.bisq-network</groupId>
            <artifactId>jsocks</artifactId>
            <!-- v0.0.3 -->
            <version>8bfc68c58d443b0ea03a8e8ec352e120fd020127</version>
        </dependency>
        <dependency>
            <groupId>io.github.oshai</groupId>
            <artifactId>kotlin-logging-jvm</artifactId>
            <version>8.0.02</version>
        </dependency>
    </dependencies>
</project>
